services:
  mcpo:
    build: .
    container_name: mcpo
    image: ghcr.io/alephpiece/mcpo # or alephpiece/mcpo from dockerhub
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - E2B_API_KEY=${E2B_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - TIMEZONE=UTC
